server {
    listen 80 default_server;
    server_name wjhdev.cloud www.wjhdev.cloud 1.117.64.149 _;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://www.wjhdev.cloud$request_uri;
    }
}

server {
    listen 443 ssl default_server;
    http2 on;
    server_name wjhdev.cloud www.wjhdev.cloud;

    ssl_certificate /etc/letsencrypt/live/wjhdev.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wjhdev.cloud/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:WJHDEV_SSL:10m;
    ssl_session_timeout 10m;

    access_log /www/wwwlogs/wjh_portfolio_access.log;
    error_log /www/wwwlogs/wjh_portfolio_error.log;
    client_max_body_size 50m;

    root /var/www/wjh-portfolio/current;
    index index.html;

    location / {
        if ($host = wjhdev.cloud) {
            return 301 https://www.wjhdev.cloud$request_uri;
        }
        try_files $uri $uri/ =404;
    }
}
